// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJ_be6rHgJ1q8VjTUmuqpI2N-ZwX-tk4',
    appId: '1:331132217293:web:9540fb8749fe0bf743c684',
    messagingSenderId: '331132217293',
    projectId: 'lottery-advance',
    authDomain: 'lottery-advance.firebaseapp.com',
    storageBucket: 'lottery-advance.firebasestorage.app',
    measurementId: 'G-2WRPKYY5TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAfeOp47kMGisd4jziywNqQOuOIlXo7c',
    appId: '1:331132217293:android:81845ebb38f368f043c684',
    messagingSenderId: '331132217293',
    projectId: 'lottery-advance',
    storageBucket: 'lottery-advance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGS7nYfsGLO2oTFJgdRHovOusHwXcfIk4',
    appId: '1:331132217293:ios:67e9a92772c19ec443c684',
    messagingSenderId: '331132217293',
    projectId: 'lottery-advance',
    storageBucket: 'lottery-advance.firebasestorage.app',
    iosBundleId: 'com.example.lotteryAdvance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChJ_be6rHgJ1q8VjTUmuqpI2N-ZwX-tk4',
    appId: '1:331132217293:web:786a27eb6ada5db743c684',
    messagingSenderId: '331132217293',
    projectId: 'lottery-advance',
    authDomain: 'lottery-advance.firebaseapp.com',
    storageBucket: 'lottery-advance.firebasestorage.app',
    measurementId: 'G-6PQYKX1738',
  );
}
