// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

error ZeroAddress();
error InvalidLevel(uint8 level);
error WeightedDrawDisabled();
error InvalidRecycleBatch(uint256 requested, uint256 maximum);
error InvalidRoundId(uint256 roundId);
error InvalidRoundTimeRange();
error InvalidRoundCapacity();
error InvalidRoundPrice();
error InvalidPaymentSplitVersion(uint16 version);
error InvalidScheduleSignature();
error InvalidSignatureLength(uint256 length);
error InvalidSignatureS();
error InvalidSignatureV(uint8 v);
error RoundConfigMismatch(uint256 roundId);
error RoundAlreadySettled(uint256 roundId);
error RoundNotInitialized(uint256 roundId);
error RoundNotStarted(uint256 roundId);
error PendingRoundRecycles(uint256 roundId, uint256 pending);
error UsdcTokenLocked();
error LegacyActivationDisabled();
error IncorrectRoundPayment();
error RoundUsdcDisabled();
error TokenTransferFailed();
error LevelEmergencyPaused(uint8 level);
error RoundTicketAlreadyActive(uint256 roundId, address player);
error RoundParentAlreadyClosed(uint256 roundId, uint256 parentCellId);
error InvalidRoundCell(uint256 roundId, uint256 cellId);
